//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaDeportesWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    
    public partial class tiendaEntities : DbContext
    {
        public tiendaEntities()
            : base("name=tiendaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORIAS> CATEGORIAS { get; set; }
        public virtual DbSet<DOMINIOS> DOMINIOS { get; set; }
        public virtual DbSet<FABRICANTES> FABRICANTES { get; set; }
        public virtual DbSet<PERSONAS> PERSONAS { get; set; }
        public virtual DbSet<PRODUCTOS> PRODUCTOS { get; set; }
        public virtual DbSet<VENTA_PRODUCTOS> VENTA_PRODUCTOS { get; set; }
        public virtual DbSet<VENTAS> VENTAS { get; set; }

        public virtual int Prc_Add_Carrito(Nullable<int> idProducto, Nullable<decimal> idPersona, string tipoPersona)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));

            var idPersonaParameter = idPersona.HasValue ?
                new ObjectParameter("IdPersona", idPersona) :
                new ObjectParameter("IdPersona", typeof(decimal));

            var tipoPersonaParameter = tipoPersona != null ?
                new ObjectParameter("TipoPersona", tipoPersona) :
                new ObjectParameter("TipoPersona", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Prc_Add_Carrito", idProductoParameter, idPersonaParameter, tipoPersonaParameter);
        }
    }
}
