//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaDeportesWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONAS()
        {
            this.VENTAS = new HashSet<VENTAS>();
        }
    
        public decimal ID_PERSONA { get; set; }
        public string NOM_PERSONA { get; set; }
        public string APE_PERSONA { get; set; }
        public decimal TEL_PERSONA { get; set; }
        public string EMAIL_PERSONA { get; set; }
        public string DIR_PERSONA { get; set; }
        public string CONTRASENA { get; set; }
        public string TIPO_PERSONA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENTAS> VENTAS { get; set; }
    }
}
