//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaDeportesWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTOS()
        {
            this.VENTA_PRODUCTOS = new HashSet<VENTA_PRODUCTOS>();
        }
    
        public int ID_PRODUCTO { get; set; }
        public string NOM_PRODUCTO { get; set; }
        public string DET_PRODUCTO { get; set; }
        public decimal PRECIO_ACTUAL { get; set; }
        public int UND_DISPONIBLES { get; set; }
        public int ID_CATEGORIA { get; set; }
        public int ID_FABRICANTE { get; set; }
        public string FOTO_PRODUCTO { get; set; }
    
        public virtual CATEGORIAS CATEGORIAS { get; set; }
        public virtual FABRICANTES FABRICANTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENTA_PRODUCTOS> VENTA_PRODUCTOS { get; set; }
    }
}
