//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaDeportesWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA_PRODUCTOS
    {
        public int ID_VENTA_PROD { get; set; }
        public int ID_VENTA { get; set; }
        public int ID_PRODUCTO { get; set; }
        public decimal PRECIO_VENTA { get; set; }
        public int CANTIDAD { get; set; }
    
        public virtual PRODUCTOS PRODUCTOS { get; set; }
        public virtual VENTAS VENTAS { get; set; }
    }
}
